// Generated by CoffeeScript 1.10.0
(function() {
  var $, ClassDecorator, WindowManager,
    slice = [].slice;

  WindowManager = require('./wmgr');

  ClassDecorator = require('./decorators').ClassDecorator;

  $ = require('../jquery-3.1.0.js');

  console.log("Hello");

  $(document).ready(function() {
    console.log("Greetings from WindowManager");
    document.windowManager = new WindowManager({
      parent: document.body
    });
    document.windowManager.hello = function() {
      return console.log("Hello");
    };
    document.windowManager = new ClassDecorator({
      object: document.windowManager,
      pre: function() {
        var args, key, value;
        key = arguments[0], value = arguments[1], args = 3 <= arguments.length ? slice.call(arguments, 2) : [];
        console.log("Called/Requested " + key);
        if (value != null) {
          console.log("Got " + value);
        }
        if ((args != null) && args.len) {
          console.log("With arguments:");
          return console.log.apply(console, args);
        }
      }
    });
    document.windowManager.createNewWindow({
      title: 'hello',
      x: 300,
      y: 300
    });
    return document.windowManager.createNewWindow({
      title: 'bye',
      x: 500,
      y: 300
    });
  });

}).call(this);
