// Generated by CoffeeScript 1.10.0
(function() {
  var $, Window;

  $ = require('../jquery-3.1.0');

  Window = (function() {
    function Window(args) {
      var bar, body, button, close, counter, j, len, minimize, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, ref8, toggleSize;
      this.parent = args.parent, this.x = (ref = args.x) != null ? ref : 50, this.y = (ref1 = args.y) != null ? ref1 : 50, this.width = (ref2 = args.width) != null ? ref2 : 800, this.height = (ref3 = args.height) != null ? ref3 : 600, this.buttonSize = (ref4 = args.buttonSize) != null ? ref4 : 60, this.title = (ref5 = args.title) != null ? ref5 : "", this.buttonSpacing = (ref6 = args.buttonSpacing) != null ? ref6 : 12;
      ref7 = this.divs(6, 'popup-element'), this.dom = ref7[0], bar = ref7[1], body = ref7[2], close = ref7[3], minimize = ref7[4], toggleSize = ref7[5];
      bar.innerHtml = this.title;
      $(this.dom).addClass('popup');
      $(this.dom).append(bar, body);
      $(this.dom).css({
        top: this.y + "px",
        left: this.x + "px",
        width: this.width + "px",
        height: this.height + "px"
      });
      $(bar).addClass('popup-bar').css({
        height: (this.buttonSize * 1.33) + "px"
      });
      $(bar).append([close, minimize, toggleSize]);
      $(body).addClass('popup-body');
      $([close, minimize, toggleSize]).addClass('popup-bar-button').css("width", this.buttonSize + "px").css("height", this.buttonSize + "px");
      counter = this.buttonSpacing;
      ref8 = [close, minimize, toggleSize];
      for (j = 0, len = ref8.length; j < len; j++) {
        button = ref8[j];
        $(button).css("right", counter + "px");
        counter += this.buttonSpacing + this.buttonSize;
      }
    }

    Window.prototype.divs = function(count, classes) {
      var dom, doms, i;
      i = 0;
      doms = [];
      while (i < count) {
        dom = $('<div>');
        if (classes) {
          dom.addClass(classes);
        }
        doms.push(dom[0]);
        i++;
      }
      console.log(doms);
      return doms;
    };

    return Window;

  })();

  module.exports = Window;

}).call(this);
