// Generated by CoffeeScript 1.10.0
(function() {
  var Window, WindowManager,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Window = require('./window');

  WindowManager = (function() {
    function WindowManager(args) {
      this.createNewWindow = bind(this.createNewWindow, this);
      var ref;
      this.parent = args.parent, this.buttonSize = (ref = args.buttonSize) != null ? ref : 80;
      this.windows = [];
    }

    WindowManager.prototype.createNewWindow = function(args) {
      var ret;
      if (args == null) {
        args = {};
      }
      args.parent = this;
      ret = new Window(args);
      console.log("this:", this);
      this.parent.appendChild(ret.dom);
      return this.windows.push(ret);
    };

    return WindowManager;

  })();

  module.exports = WindowManager;

}).call(this);
