// Generated by CoffeeScript 1.10.0
(function() {
  var Window, WindowManager,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Window = require('./window');

  WindowManager = (function() {
    function WindowManager(args) {
      this.toggleSize = bind(this.toggleSize, this);
      this.toggleShow = bind(this.toggleShow, this);
      this.click = bind(this.click, this);
      this.createNewWindow = bind(this.createNewWindow, this);
      var ref;
      this.parent = args.parent, this.buttonSize = (ref = args.buttonSize) != null ? ref : 80;
      this.windows = [];
    }

    WindowManager.prototype.createNewWindow = function(args) {
      var ret;
      if (args == null) {
        args = {};
      }
      args.parent = this;
      args.zindex = this.windows.length + 1;
      ret = new Window(args);
      console.log("this:", this);
      this.parent.appendChild(ret.dom);
      return this.windows.push(ret);
    };

    WindowManager.prototype.click = function(iwin) {
      var i, len, ref, win;
      ref = this.windows;
      for (i = 0, len = ref.length; i < len; i++) {
        win = ref[i];
        if (iwin !== win) {
          win.changeZIndex(-1);
        }
      }
      return iwin.changeZIndex(1);
    };

    WindowManager.prototype.toggleShow = function(iwin) {
      return console.log("toggleShow: not implemented");
    };

    WindowManager.prototype.toggleSize = function(iwin) {
      return console.log("toggleSize: not implemented");
    };

    return WindowManager;

  })();

  module.exports = WindowManager;

}).call(this);
